/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Cars } from "./Cars";
export type { SpaceAdventures } from "./SpaceAdventures";
export type { SpaceCoins } from "./SpaceCoins";
export type { SpaceShips } from "./SpaceShips";
